DROP TABLE IF EXISTS "books" CASCADE;
DROP TABLE IF EXISTS "autors" CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS orders CASCADE;

CREATE TABLE IF NOT EXISTS customers
(
    customer_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    first_name CHARACTER VARYING(255) NOT NULL,
    last_name CHARACTER VARYING(255) NOT NULL,
    email CHARACTER VARYING(255) NOT NULL,
    contact_number CHARACTER VARYING(255) NOT NULL,
    CONSTRAINT pk_customers PRIMARY KEY (customer_id)
);

CREATE TABLE IF NOT EXISTS products
(
    product_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name CHARACTER VARYING(255) NOT NULL,
    description CHARACTER VARYING(255) NOT NULL,
    price FLOAT NOT NULL,
    quantity_in_stock BIGINT NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS orders
(
    order_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    customer_id BIGINT NOT NULL,
    order_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    shipping_address CHARACTER VARYING(255) NOT NULL,
    total_price FLOAT NOT NULL,
    order_status CHARACTER VARYING(50) NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (order_id),
    CONSTRAINT fk_orders_customer_id FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
);

CREATE TABLE IF NOT EXISTS order_products
(
    order_id BIGINT NOT NULL,
    product_id       BIGINT NOT NULL,
    CONSTRAINT pk_order_products PRIMARY KEY (order_id, product_id),
    CONSTRAINT fk_order_products_order_id FOREIGN KEY (order_id) REFERENCES orders (order_id),
    CONSTRAINT fk_order_products_product_id FOREIGN KEY (product_id) REFERENCES products (product_id)
);

