DROP TABLE IF EXISTS "books" CASCADE;
DROP TABLE IF EXISTS "autors" CASCADE;
CREATE TABLE IF NOT EXISTS PUBLIC."autors"
(
    "id"   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "name" CHARACTER VARYING(255) NOT NULL,
    CONSTRAINT pk_autors PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS PUBLIC."books"
(
    "id"        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "title"     CHARACTER VARYING(255) NOT NULL,
    "author_id" BIGINT NOT NULL,
    CONSTRAINT pk_books PRIMARY KEY (id),
    CONSTRAINT fk_autors FOREIGN KEY (author_id) REFERENCES autors (id)
);

/*CREATE TABLE IF NOT EXISTS PUBLIC."autors_books"
(
    author_id BIGINT NOT NULL,
    book_id       BIGINT NOT NULL,
    CONSTRAINT pk_autors_books PRIMARY KEY (author_id, book_id),
    CONSTRAINT fk_autors_books_author_id FOREIGN KEY (author_id) REFERENCES autors (id),
    CONSTRAINT fk_autors_books_book_id FOREIGN KEY (book_id) REFERENCES books (id)
);
*/

